import React, { useMemo, useState } from 'react';
import { Banknote, Plus, Trash2, TrendingDown, TrendingUp, Wallet, X, CheckCircle2 } from 'lucide-react';
import { Booking, BusinessExpense, BusinessProfile, Invoice } from '../../types';

interface FinanceViewProps { bookings?: Booking[]; invoices?: Invoice[]; profile?: BusinessProfile; onUpdateBooking?: (id:string, updates:Partial<Booking>)=>Promise<Booking>; }
const EXPENSE_KEY='together-events-business-expenses-v1';
const categories:BusinessExpense['category'][]=['Operations','Transport','Staff','Marketing','Office','Other'];

export const FinanceView:React.FC<FinanceViewProps>=({bookings=[],invoices=[],profile,onUpdateBooking})=>{
 const currency=profile?.currencySymbol||'Rs. ';
 const [expenses,setExpenses]=useState<BusinessExpense[]>(()=>{try{const raw=localStorage.getItem(EXPENSE_KEY);return raw?JSON.parse(raw):[]}catch{return[]}});
 const [isOpen,setIsOpen]=useState(false);
 const [paymentOpen,setPaymentOpen]=useState<{bookingId:string;vendorId:string}|null>(null);
 const [paymentForm,setPaymentForm]=useState({amount:'',date:new Date().toISOString().slice(0,10),method:'Cash',notes:''});
 const [form,setForm]=useState({title:'',category:'Operations' as BusinessExpense['category'],amount:'',date:new Date().toISOString().slice(0,10),notes:''});
 const money=(n:number)=>`${currency}${Number(n||0).toLocaleString()}`;
 const revenue=useMemo(()=>invoices.reduce((sum,invoice)=>{const amount=Number(invoice.totalAmount||0);if(amount>0)return sum+amount;return sum+(invoice.items||[]).reduce((s,item)=>s+Number(item.total||Number(item.quantity||0)*Number(item.unitPrice||0)),0)},0),[invoices]);
 const vendorCommitted=useMemo(()=>bookings.reduce((sum,b)=>sum+(b.assignedVendors||[]).reduce((s,v)=>s+Number(v.agreedAmount||0),0),0),[bookings]);
 const vendorPaid=useMemo(()=>bookings.reduce((sum,b)=>sum+(b.assignedVendors||[]).reduce((s,v)=>s+Math.min(Number(v.paidAmount||0),Number(v.agreedAmount||0)),0),0),[bookings]);
 const otherExpenses=expenses.reduce((sum,e)=>sum+Number(e.amount||0),0);
 const netProfit=revenue-vendorPaid-otherExpenses; const expectedProfit=revenue-vendorCommitted-otherExpenses;
 const saveExpenses=(next:BusinessExpense[])=>{setExpenses(next);localStorage.setItem(EXPENSE_KEY,JSON.stringify(next));};
 const addExpense=(e:React.FormEvent)=>{e.preventDefault();const amount=Number(form.amount||0);if(!form.title.trim()||amount<=0)return;const expense:BusinessExpense={id:crypto.randomUUID(),title:form.title.trim(),category:form.category,amount,date:form.date,notes:form.notes.trim(),createdAt:new Date().toISOString()};saveExpenses([expense,...expenses]);setForm({title:'',category:'Operations',amount:'',date:new Date().toISOString().slice(0,10),notes:''});setIsOpen(false)};
 const openVendorPaymentPicker=()=>{setSelectedVendorRow(null);setVendorPaymentPickerOpen(true);}; const continueVendorPayment=()=>{if(!selectedVendorRow)return;setVendorPaymentPickerOpen(false);openPayment(selectedVendorRow.bookingId,selectedVendorRow.vendorId);};
 const openPayment=(bookingId:string,vendorId:string)=>{setPaymentForm({amount:'',date:new Date().toISOString().slice(0,10),method:'Cash',notes:''});setPaymentOpen({bookingId,vendorId});};
 const savePayment=async(e:React.FormEvent)=>{e.preventDefault();if(!paymentOpen||!onUpdateBooking)return;const booking=bookings.find(b=>b.id===paymentOpen.bookingId);const assignment=booking?.assignedVendors?.find(v=>v.vendorId===paymentOpen.vendorId);if(!booking||!assignment)return;const amount=Number(paymentForm.amount||0);const nextPaid=Math.min(Number(assignment.agreedAmount||0),Number(assignment.paidAmount||0)+amount);if(amount<=0)return;await onUpdateBooking(booking.id,{assignedVendors:booking.assignedVendors.map(v=>v.vendorId===assignment.vendorId?{...v,paidAmount:nextPaid,paymentStatus:nextPaid>=Number(v.agreedAmount||0)?'Paid':'Pending',paymentDate:paymentForm.date,paymentMethod:paymentForm.method,paymentNotes:paymentForm.notes.trim()}:v)});setPaymentOpen(null);};
 const vendorRows=bookings.flatMap(b=>(b.assignedVendors||[]).map(v=>({booking:b,vendor:v})));
 return <div className="space-y-6 animate-in fade-in duration-200">
  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><span className="text-[10px] font-medium uppercase tracking-[0.16em] text-slate-400">Financial Control</span><h1 className="text-2xl font-semibold tracking-tight text-[#0f172a] mt-1">Profit &amp; Loss</h1><p className="text-slate-500 text-sm mt-1">See business revenue, vendor payments, expenses and actual profit.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={openVendorPaymentPicker} disabled={vendorRows.length===0} className="inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-2xl bg-emerald-600 text-white text-xs font-medium shadow-lg shadow-emerald-900/10 disabled:opacity-50"><Banknote className="w-4 h-4"/> Vendor Payment</button><button type="button" onClick={()=>setIsOpen(true)} className="inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-2xl bg-[#0f172a] text-white text-xs font-medium shadow-lg shadow-slate-900/10"><Plus className="w-4 h-4"/> Add Expense</button></div></div>
  <div className="grid grid-cols-2 lg:grid-cols-5 gap-4"><div className="glass-panel p-5"><Banknote className="w-5 h-5 text-slate-500"/><span className="block text-[10px] uppercase tracking-widest font-medium text-slate-400 mt-4">Total Business</span><strong className="block text-xl font-medium mt-2">{money(revenue)}</strong><span className="text-[10px] text-slate-500">Invoice revenue</span></div><div className="glass-panel p-5"><Wallet className="w-5 h-5 text-slate-500"/><span className="block text-[10px] uppercase tracking-widest font-medium text-slate-400 mt-4">Vendor Paid</span><strong className="block text-xl font-medium mt-2">{money(vendorPaid)}</strong><span className="text-[10px] text-slate-500">Recorded payments</span></div><div className="glass-panel p-5"><TrendingDown className="w-5 h-5 text-slate-500"/><span className="block text-[10px] uppercase tracking-widest font-medium text-slate-400 mt-4">Other Expenses</span><strong className="block text-xl font-medium mt-2">{money(otherExpenses)}</strong><span className="text-[10px] text-slate-500">Manual expenses</span></div><div className="glass-panel p-5"><TrendingDown className="w-5 h-5 text-slate-500"/><span className="block text-[10px] uppercase tracking-widest font-medium text-slate-400 mt-4">Vendor Commitments</span><strong className="block text-xl font-medium mt-2">{money(vendorCommitted)}</strong><span className="text-[10px] text-slate-500">Agreed vendor cost</span></div><div className={`glass-panel p-5 col-span-2 lg:col-span-1 ${netProfit>=0?'bg-white/75':'bg-rose-50/70'}`}><TrendingUp className="w-5 h-5 text-slate-500"/><span className="block text-[10px] uppercase tracking-widest font-medium text-slate-400 mt-4">Net Profit</span><strong className={`block text-xl font-medium mt-2 ${netProfit>=0?'text-emerald-700':'text-rose-600'}`}>{money(netProfit)}</strong><span className="text-[10px] text-slate-500">Revenue − paid vendors − expenses</span></div></div>
  <div className="glass-panel p-6 sm:p-7"><div className="flex items-center justify-between pb-4 border-b border-white/60"><div><h2 className="text-lg font-semibold">Vendor Payments</h2><p className="text-xs text-slate-500 mt-1">Record payments against vendors assigned to each booking.</p></div></div>{vendorRows.length===0?<div className="py-10 text-center text-sm text-slate-400">No vendors are assigned to bookings yet. Assign a vendor from Bookings first.</div>:<div className="overflow-x-auto mt-4"><table className="w-full text-left"><thead className="text-[10px] uppercase tracking-widest text-slate-400 font-medium border-b border-white/60"><tr><th className="pb-3">Vendor</th><th className="pb-3">Event</th><th className="pb-3">Agreed</th><th className="pb-3">Paid</th><th className="pb-3">Balance</th><th className="pb-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-white/50">{vendorRows.map(({booking:b,vendor:v})=>{const paid=Math.min(Number(v.paidAmount||0),Number(v.agreedAmount||0));const balance=Math.max(0,Number(v.agreedAmount||0)-paid);return <tr key={`${b.id}-${v.id}`}><td className="py-3 text-xs font-medium">{v.vendorName}</td><td className="py-3 text-xs text-slate-500">{b.clientName} • {b.eventDate}</td><td className="py-3 text-xs">{money(v.agreedAmount)}</td><td className="py-3 text-xs text-emerald-700 font-medium">{money(paid)}</td><td className="py-3 text-xs text-amber-700">{money(balance)}</td><td className="py-3 text-right"><button type="button" onClick={()=>openPayment(b.id,v.vendorId)} className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-[#0f172a] text-white text-[10px] font-medium hover:bg-slate-800">{balance>0?<><Plus className="w-3 h-3"/> Record Payment</>:<><CheckCircle2 className="w-3 h-3"/> Paid</>}</button></td></tr>})}</tbody></table></div>}</div>
  <div className="glass-panel p-6 sm:p-7"><div className="flex items-center justify-between pb-4 border-b border-white/60"><div><h2 className="text-lg font-semibold">Profit &amp; Cost Summary</h2><p className="text-xs text-slate-500 mt-1">Expected profit after all agreed vendor costs: {money(expectedProfit)}.</p></div></div><div className="mt-6 space-y-4"><div><div className="flex justify-between text-xs font-medium mb-1.5"><span>Business Revenue</span><span>{money(revenue)}</span></div><div className="h-2 rounded-full bg-slate-200/70 overflow-hidden"><div className="h-full rounded-full bg-slate-900" style={{width:revenue?'100%':'0%'}}/></div></div><div><div className="flex justify-between text-xs font-medium mb-1.5"><span>Vendor Paid</span><span>{money(vendorPaid)}</span></div><div className="h-2 rounded-full bg-slate-200/70 overflow-hidden"><div className="h-full rounded-full bg-slate-500" style={{width:revenue?`${Math.min(100,vendorPaid/revenue*100)}%`:'0%'}}/></div></div><div><div className="flex justify-between text-xs font-medium mb-1.5"><span>Other Expenses</span><span>{money(otherExpenses)}</span></div><div className="h-2 rounded-full bg-slate-200/70 overflow-hidden"><div className="h-full rounded-full bg-slate-400" style={{width:revenue?`${Math.min(100,otherExpenses/revenue*100)}%`:'0%'}}/></div></div></div></div>
  <div className="glass-panel p-6 sm:p-7"><div className="flex items-center justify-between mb-5"><div><h2 className="text-base font-semibold">Business Expenses</h2><p className="text-xs text-slate-500 mt-1">Add office, transport, staff, marketing and other running costs.</p></div><button type="button" onClick={()=>setIsOpen(true)} className="text-xs font-medium text-slate-600 inline-flex items-center gap-1"><Plus className="w-3.5 h-3.5"/> Add</button></div>{expenses.length===0?<div className="py-10 text-center text-sm text-slate-400">No manual expenses added yet.</div>:<div className="overflow-x-auto"><table className="w-full text-left"><thead className="text-[10px] uppercase tracking-widest text-slate-400 font-medium border-b border-white/60"><tr><th className="pb-3">Expense</th><th className="pb-3">Category</th><th className="pb-3">Date</th><th className="pb-3 text-right">Amount</th><th className="pb-3 w-10"/></tr></thead><tbody className="divide-y divide-white/50">{expenses.map(expense=><tr key={expense.id}><td className="py-3 text-xs font-medium">{expense.title}</td><td className="py-3 text-xs text-slate-500">{expense.category}</td><td className="py-3 text-xs text-slate-500">{expense.date}</td><td className="py-3 text-xs font-medium text-right">{money(expense.amount)}</td><td className="py-3 text-right"><button type="button" onClick={()=>saveExpenses(expenses.filter(item=>item.id!==expense.id))} className="p-1.5 rounded-lg text-slate-400 hover:text-rose-600 hover:bg-rose-50"><Trash2 className="w-3.5 h-3.5"/></button></td></tr>)}</tbody></table></div>}</div>
  {vendorPaymentPickerOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/20 backdrop-blur-sm"><div className="w-full max-w-md glass-panel p-6 shadow-2xl"><div className="flex items-center justify-between mb-5"><div><h2 className="text-lg font-semibold">Vendor Payment</h2><p className="text-xs text-slate-500 mt-1">Select the vendor and event you are paying for.</p></div><button type="button" onClick={()=>setVendorPaymentPickerOpen(false)} className="p-2 rounded-xl hover:bg-white/70"><X className="w-4 h-4"/></button></div><div><label className="text-xs font-medium text-slate-600">Vendor / Event</label><select value={selectedVendorRow?selectedVendorRow.bookingId+'|'+selectedVendorRow.vendorId:''} onChange={e=>{const parts=e.target.value.split('|');setSelectedVendorRow(parts.length===2?{bookingId:parts[0],vendorId:parts[1]}:null)}} className="mt-1 w-full px-3 py-2.5 rounded-xl bg-white/80 border border-white/90 text-sm"><option value="">Select vendor</option>{vendorRows.map(({booking:b,vendor:v})=><option key={b.id+'|'+v.vendorId} value={b.id+'|'+v.vendorId}>{v.vendorName} — {b.clientName} ({b.eventDate})</option>)}</select></div><button type="button" disabled={!selectedVendorRow} onClick={continueVendorPayment} className="mt-5 w-full py-2.5 rounded-xl bg-[#0f172a] text-white text-xs font-medium disabled:opacity-50">Continue to Payment</button></div></div>}
  {isOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/20 backdrop-blur-sm"><form onSubmit={addExpense} className="w-full max-w-md glass-panel p-6 shadow-2xl"><div className="flex items-center justify-between mb-5"><div><h2 className="text-lg font-semibold">Add Business Expense</h2><p className="text-xs text-slate-500 mt-1">This amount will reduce Net Profit.</p></div><button type="button" onClick={()=>setIsOpen(false)} className="p-2 rounded-xl hover:bg-white/70"><X className="w-4 h-4"/></button></div><div className="space-y-4"><div><label className="text-xs font-medium text-slate-600">Expense Name</label><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Office electricity" className="mt-1 w-full px-3 py-2.5 rounded-xl bg-white/80 border border-white/90 text-sm"/></div><div className="grid grid-cols-2 gap-3"><div><label className="text-xs font-medium text-slate-600">Amount</label><input required min="0.01" type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0" className="mt-1 w-full px-3 py-2.5 rounded-xl bg-white/80 border border-white/90 text-sm"/></div><div><label className="text-xs font-medium text-slate-600">Date</label><input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className="mt-1 w-full px-3 py-2.5 rounded-xl bg-white/80 border border-white/90 text-sm"/></div></div><div><label className="text-xs font-medium text-slate-600">Category</label><select value={form.category} onChange={e=>setForm({...form,category:e.target.value as BusinessExpense['category']})} className="mt-1 w-full px-3 py-2.5 rounded-xl bg-white/80 border border-white/90 text-sm">{categories.map(c=><option key={c}>{c}</option>)}</select></div><div><label className="text-xs font-medium text-slate-600">Notes</label><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows={3} className="mt-1 w-full px-3 py-2.5 rounded-xl bg-white/80 border border-white/90 text-sm resize-none"/></div></div><button type="submit" className="mt-5 w-full py-2.5 rounded-xl bg-[#0f172a] text-white text-xs font-medium">Save Expense</button></form></div>}
  {paymentOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/20 backdrop-blur-sm"><form onSubmit={savePayment} className="w-full max-w-md glass-panel p-6 shadow-2xl"><div className="flex items-center justify-between mb-5"><div><h2 className="text-lg font-semibold">Record Vendor Payment</h2><p className="text-xs text-slate-500 mt-1">Enter the amount you are paying this vendor now.</p></div><button type="button" onClick={()=>setPaymentOpen(null)} className="p-2 rounded-xl hover:bg-white/70"><X className="w-4 h-4"/></button></div><div className="space-y-4"><div><label className="text-xs font-medium text-slate-600">Payment Amount</label><input required min="0.01" type="number" value={paymentForm.amount} onChange={e=>setPaymentForm({...paymentForm,amount:e.target.value})} className="mt-1 w-full px-3 py-2.5 rounded-xl bg-white/80 border border-white/90 text-sm"/></div><div className="grid grid-cols-2 gap-3"><div><label className="text-xs font-medium text-slate-600">Payment Date</label><input required type="date" value={paymentForm.date} onChange={e=>setPaymentForm({...paymentForm,date:e.target.value})} className="mt-1 w-full px-3 py-2.5 rounded-xl bg-white/80 border border-white/90 text-sm"/></div><div><label className="text-xs font-medium text-slate-600">Method</label><select value={paymentForm.method} onChange={e=>setPaymentForm({...paymentForm,method:e.target.value})} className="mt-1 w-full px-3 py-2.5 rounded-xl bg-white/80 border border-white/90 text-sm"><option>Cash</option><option>Bank Transfer</option><option>JazzCash</option><option>EasyPaisa</option><option>Other</option></select></div></div><div><label className="text-xs font-medium text-slate-600">Notes</label><textarea value={paymentForm.notes} onChange={e=>setPaymentForm({...paymentForm,notes:e.target.value})} rows={3} className="mt-1 w-full px-3 py-2.5 rounded-xl bg-white/80 border border-white/90 text-sm"/></div></div><button type="submit" className="mt-5 w-full py-2.5 rounded-xl bg-[#0f172a] text-white text-xs font-medium">Save Payment</button></form></div>}
 </div>;
};