import {
  BusinessProfile,
  InvoiceSettings,
  Client,
  Vendor,
  Booking,
  Invoice
} from '../types';

export const initialBusinessProfile: BusinessProfile = {
  businessName: 'Together Events',
  tagline: 'Luxury Wedding & Event Planning',
  ownerName: 'Zainab Qureshi',
  phone: '+92 300 1234567',
  whatsApp: '+92 300 1234567',
  email: 'hello@togetherevents.com',
  website: 'www.togetherevents.com',
  address: 'Model Town, Club Road',
  city: 'Bahawalpur',
  country: 'Pakistan',
  taxNumber: 'PK-NTN-9842103',
  registrationNumber: 'SECP-REG-44219',
  logoUrl: '',
  signatureUrl: '',
  invoiceFooterText: 'Thank you for trusting Together Events to create your unforgettable celebration.',
  defaultTerms: '1. A non-refundable advance of 30% is required to secure the event date.\n2. 50% payment is due 14 days before the event.\n3. The remaining balance must be settled 24 hours prior to event commencement.\n4. Changes to guest count or menu must be finalized 7 days in advance.',
  defaultCurrency: 'PKR',
  currencySymbol: 'Rs. ',
  invoicePrefix: 'TE-',
  invoiceStartingNumber: 1001,
};

export const initialInvoiceSettings: InvoiceSettings = {
  documentTitle: 'BOOKING CONFIRMATION',
  defaultTemplate: 'modern',
  showLogo: true,
  showSignature: true,
  showBusinessAddress: true,
  showBillingAddress: true,
  showContactInfo: true,
  showPhone: true,
  showEmail: true,
  fontSize: 'medium',
  bodySize: 'medium',
  headingSize: 'medium',
  dateFormat: 'MMM DD, YYYY',
  whatsappMessageTemplate: 'Dear {{client_name}},\n\nThank you for choosing {{business_name}}. Please find your invoice details below for your {{event_type}} event.\n\nThank you!',
  emailMessageTemplate: 'Dear {{client_name}},\n\nThank you for choosing {{business_name}}. Please find your invoice details below for your {{event_type}} event.\n\nPlease contact us if you have any questions.',
};

export const initialClients: Client[] = [
  {
    id: 'cli-1',
    fullName: 'Sarah & Farhan Ahmed',
    phone: '+92 321 4455667',
    whatsApp: '+92 321 4455667',
    email: 'sarah.farhan@gmail.com',
    billingAddress: 'House 42, Sector F, Gulberg Colony',
    city: 'Lahore',
    country: 'Pakistan',
    notes: 'Bride requested pastel floral themes with fairy light canopy for Mehndi & Baraat.',
    createdAt: '2026-08-10T10:00:00Z',
  },
  {
    id: 'cli-2',
    fullName: 'Ayesha & Bilal Malik',
    phone: '+92 333 8901234',
    whatsApp: '+92 333 8901234',
    email: 'ayesha.malik@outlook.com',
    billingAddress: 'Villa 14, Royal Palm Residency',
    city: 'Bahawalpur',
    country: 'Pakistan',
    notes: 'Grand Walima reception with 650 guests. VIP family stage with crystal chandelier.',
    createdAt: '2026-08-15T12:30:00Z',
  },
  {
    id: 'cli-3',
    fullName: 'Dr. Tariq & Dr. Rehana',
    phone: '+92 301 5567890',
    whatsApp: '+92 301 5567890',
    email: 'tariq.rehana@medcare.com',
    billingAddress: 'Street 9, Cantt Area',
    city: 'Multan',
    country: 'Pakistan',
    notes: 'Daughter Nikkah ceremony. Intimate gathering of 200 guests with live qawwali.',
    createdAt: '2026-08-20T09:15:00Z',
  },
  {
    id: 'cli-4',
    fullName: 'Apex Global Enterprises',
    phone: '+92 312 9988776',
    whatsApp: '+92 312 9988776',
    email: 'events@apexglobal.pk',
    billingAddress: 'Floor 7, Executive Heights, Blue Area',
    city: 'Islamabad',
    country: 'Pakistan',
    notes: 'Annual Corporate Gala & Excellence Awards with 350 executives.',
    createdAt: '2026-08-25T14:00:00Z',
  },
];

export const initialVendors: Vendor[] = [
  {
    id: 'ven-1',
    vendorName: 'Royal Flora & Decors',
    category: 'Decorator',
    contactPerson: 'Kashif Mehmood',
    phone: '+92 322 1122334',
    whatsApp: '+92 322 1122334',
    email: 'decor@royalflora.com',
    address: 'Circular Road, Flower Market',
    services: 'Stage design, floral arches, entrance tunnels, bespoke candlescapes',
    paymentTerms: '40% advance, 60% on setup day',
    notes: 'Always delivers fresh Ecuadorian roses and high-end drapery.',
    createdAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'ven-2',
    vendorName: 'Nawab Royal Catering',
    category: 'Caterer',
    contactPerson: 'Chef Asif Qureshi',
    phone: '+92 300 7766554',
    whatsApp: '+92 300 7766554',
    email: 'catering@nawabroyal.pk',
    address: 'Circular Road, Bahawalpur',
    services: 'Wedding menus, live BBQ, desserts, beverage counters',
    paymentTerms: '50% advance, 50% after event',
    notes: 'Premium Pakistani and continental catering.',
    createdAt: '2026-07-05T10:00:00Z',
  },
];