import React, { useState } from 'react';
import { Search, Calendar, MapPin, Users, Edit2, Trash2, Clock, Banknote, CheckCircle2 } from 'lucide-react';
import { Booking, Client, Vendor, BookingStatus, BusinessProfile } from '../../types';
import { StatusBadge } from '../common/StatusBadge';
import { Modal } from '../common/Modal';
import { EmptyState } from '../common/EmptyState';
import { initialBusinessProfile } from '../../services/mockData';

interface BookingsViewProps { bookings?: Booking[]; clients?: Client[]; vendors?: Vendor[]; profile?: BusinessProfile; onUpdateBooking: (id: string, updates: Partial<Booking>) => Promise<Booking>; onDeleteBooking: (id: string) => Promise<boolean>; onAssignVendor: (bookingId: string, vendorData: any) => Promise<Booking>; onRemoveVendor: (bookingId: string, bookingVendorId: string) => Promise<Booking>; selectedBookingForDetail?: Booking | null; onCloseDetail?: () => void; }
const BOOKING_STATUSES: BookingStatus[] = ['Inquiry', 'Confirmed', 'Completed', 'Cancelled'];
export const BookingsView: React.FC<BookingsViewProps> = ({ bookings: inputBookings = [], vendors: inputVendors = [], profile: inputProfile, onUpdateBooking, onDeleteBooking, onAssignVendor, onRemoveVendor, selectedBookingForDetail, onCloseDetail }) => {
 const profile=inputProfile||initialBusinessProfile; const bookings=Array.isArray(inputBookings)?inputBookings:[]; const vendors=Array.isArray(inputVendors)?inputVendors:[]; const [searchTerm,setSearchTerm]=useState(''); const [statusFilter,setStatusFilter]=useState('All'); const [detailBooking,setDetailBooking]=useState<Booking|null>(selectedBookingForDetail||null); const [paymentAmount,setPaymentAmount]=useState(''); const [savingAction,setSavingAction]=useState(false);
 const formatMoney=(amount:number)=>`${profile.currencySymbol||'Rs. '}${Number(amount||0).toLocaleString()}`; const filteredBookings=bookings.filter(b=>{const q=searchTerm.toLowerCase();const matches=[b.clientName,b.venue,b.package,b.eventType].some(v=>String(v||'').toLowerCase().includes(q));return matches&&(statusFilter==='All'||b.bookingStatus===statusFilter)}); React.useEffect(()=>setDetailBooking(selectedBookingForDetail||null),[selectedBookingForDetail]); const closeDetail=()=>{setDetailBooking(null);onCloseDetail?.()};
 const handleDelete=async(id:string)=>{if(!window.confirm('Are you sure you want to delete this booking?'))return;await onDeleteBooking(id);if(detailBooking?.id===id)closeDetail()}; const refreshDetail=(updated:Booking)=>setDetailBooking(updated);
 const handlePayment=async()=>{if(!detailBooking)return;const amount=Number(paymentAmount||0);if(amount<=0)return;setSavingAction(true);try{const total=Number(detailBooking.totalAmount||0);const paid=Math.min(total,Number(detailBooking.advancePaid||0)+amount);const remaining=Math.max(0,total-paid);refreshDetail(await onUpdateBooking(detailBooking.id,{advancePaid:paid,remainingAmount:remaining,paymentStatus:remaining<=0?'Paid':'Partial'}));setPaymentAmount('')}finally{setSavingAction(false)}};
 const markConfirmed=async()=>{if(!detailBooking)return;setSavingAction(true);try{const total=Number(detailBooking.totalAmount||0);const paid=Math.max(0,Math.min(total,Number(detailBooking.advancePaid||0)));const remaining=Math.max(0,total-paid);refreshDetail(await onUpdateBooking(detailBooking.id,{bookingStatus:'Confirmed',advancePaid:paid,remainingAmount:remaining,paymentStatus:remaining<=0?'Paid':paid>0?'Partial':'Pending'}))}finally{setSavingAction(false)}};
 const markCompleted=async()=>{if(!detailBooking)return;setSavingAction(true);try{refreshDetail(await onUpdateBooking(detailBooking.id,{bookingStatus:'Completed'}))}finally{setSavingAction(false)}};
 const markCancelled=async()=>{if(!detailBooking)return;if(!window.confirm('Cancel this event? It will be removed from upcoming events and calendar active events.'))return;setSavingAction(true);try{refreshDetail(await onUpdateBooking(detailBooking.id,{bookingStatus:'Cancelled'}))}finally{setSavingAction(false)}};
 return <div className="space-y-6 animate-in fade-in duration-150"><div><h1 className="text-2xl font-semibold tracking-tight text-[#0f172a]">Bookings</h1><p className="text-slate-500 text-sm mt-0.5">Bookings are created automatically when you save a New Invoice.</p></div>
 <div className="glass-card p-4 flex flex-col md:flex-row gap-3 items-stretch md:items-center justify-between"><div className="relative flex-1"><Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2"/><input type="text" placeholder="Search by client, event, venue or package..." value={searchTerm} onChange={e=>setSearchTerm(e.target.value)} className="w-full pl-9 pr-4 py-2 text-sm bg-white/60 border border-slate-200 rounded-xl focus:outline-none"/></div><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="px-3 py-2 text-xs font-medium bg-white/60 border border-slate-200 rounded-xl text-slate-700"><option value="All">All Statuses</option>{BOOKING_STATUSES.map(s=><option key={s}>{s}</option>)}</select></div>
 {filteredBookings.length===0?<EmptyState title="No bookings yet" description="Create a New Invoice to automatically create the linked booking." icon={Calendar}/>:<div className="glass-card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left border-collapse text-sm"><thead><tr className="border-b border-slate-100 text-[10px] font-medium text-slate-400 uppercase tracking-widest"><th className="py-3 px-4">Client & Event</th><th className="py-3 px-4">Date & Time</th><th className="py-3 px-4">Venue & Guests</th><th className="py-3 px-4">Vendor</th><th className="py-3 px-4 text-right">Financials</th><th className="py-3 px-4 text-center">Status</th><th className="py-3 px-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filteredBookings.map(b=><tr key={b.id} className="hover:bg-slate-50/80 transition-colors cursor-pointer" onClick={()=>setDetailBooking(b)}><td className="py-3.5 px-4"><div className="font-medium text-slate-900">{b.clientName}</div><div className="text-xs text-slate-500 mt-0.5">{b.eventType} • {b.package}</div></td><td className="py-3.5 px-4"><div className="font-mono text-xs font-medium">{b.eventDate}</div><div className="text-xs text-slate-500 mt-0.5 flex items-center gap-1"><Clock className="w-3 h-3"/>{b.eventTime||'TBA'}</div></td><td className="py-3.5 px-4"><div className="text-xs font-medium">{b.venue||'Venue Pending'}</div><div className="text-xs text-slate-500 mt-0.5 flex items-center gap-1"><Users className="w-3 h-3"/>{b.guestCount||0} guests</div></td><td className="py-3.5 px-4"><div className="text-xs font-medium">{b.assignedVendors?.length?b.assignedVendors.map(v=>v.vendorName).join(', '):'No vendor assigned'}</div></td><td className="py-3.5 px-4 text-right"><div className="font-medium">{formatMoney(b.totalAmount)}</div><div className="text-xs text-slate-500">Rem: {formatMoney(b.remainingAmount)}</div></td><td className="py-3.5 px-4 text-center"><div className="flex flex-col items-center gap-1"><StatusBadge status={b.bookingStatus}/><StatusBadge status={b.paymentStatus}/></div></td><td className="py-3.5 px-4 text-right"><button type="button" title="Open Booking" onClick={e=>{e.stopPropagation();setDetailBooking(b)}} className="p-1.5 text-slate-600 hover:text-slate-950 hover:bg-slate-100 rounded-lg"><Edit2 className="w-4 h-4"/></button><button type="button" title="Delete Booking" onClick={e=>{e.stopPropagation();handleDelete(b.id)}} className="p-1.5 text-rose-500 hover:text-rose-700 hover:bg-rose-50 rounded-lg"><Trash2 className="w-4 h-4"/></button></td></tr>)}</tbody></table></div></div>}
 {detailBooking&&<Modal isOpen={true} onClose={closeDetail} title={detailBooking.clientName} subtitle={`${detailBooking.eventType} • ${detailBooking.eventDate}`} maxWidth="2xl"><div className="space-y-5"><div className="p-4 rounded-2xl bg-slate-50 border border-slate-200"><div className="flex flex-wrap items-center justify-between gap-3"><div><span className="text-xs text-slate-400 uppercase font-medium">Status</span><div className="flex gap-2 mt-1"><StatusBadge status={detailBooking.bookingStatus}/><StatusBadge status={detailBooking.paymentStatus}/></div></div><button type="button" onClick={()=>handleDelete(detailBooking.id)} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-xl bg-rose-50 text-rose-600 text-xs font-medium"><Trash2 className="w-3.5 h-3.5"/>Delete</button></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2 mt-4"><button type="button" disabled={savingAction||detailBooking.bookingStatus==='Completed'} onClick={markConfirmed} className="inline-flex items-center justify-center gap-2 px-3 py-2.5 rounded-xl bg-blue-600 text-white text-xs font-medium"><CheckCircle2 className="w-4 h-4"/>{detailBooking.bookingStatus==='Confirmed'?'Event Confirmed':'Confirm Event & Save'}</button><button type="button" disabled={savingAction||detailBooking.bookingStatus==='Completed'} onClick={markCompleted} className="inline-flex items-center justify-center gap-2 px-3 py-2.5 rounded-xl bg-rose-600 text-white text-xs font-medium"><CheckCircle2 className="w-4 h-4"/>{detailBooking.bookingStatus==='Completed'?'Event Completed':'Mark Event Completed'}</button><button type="button" disabled={savingAction||Number(detailBooking.remainingAmount||0)<=0} onClick={()=>document.getElementById('booking-payment-input')?.focus()} className="inline-flex items-center justify-center gap-2 px-3 py-2.5 rounded-xl bg-emerald-600 text-white text-xs font-medium"><Banknote className="w-4 h-4"/>Add Payment</button><button type="button" disabled={savingAction||detailBooking.bookingStatus==='Cancelled'} onClick={markCancelled} className="inline-flex items-center justify-center gap-2 px-3 py-2.5 rounded-xl bg-rose-50 text-rose-600 border border-rose-200 text-xs font-medium">Cancel Event</button></div></div>
 <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs"><div className="p-3 rounded-xl bg-white border"><span className="text-slate-400">Date</span><p className="font-medium mt-1">{detailBooking.eventDate}</p></div><div className="p-3 rounded-xl bg-white border"><span className="text-slate-400">Time</span><p className="font-medium mt-1">{detailBooking.eventTime||'TBA'}</p></div><div className="p-3 rounded-xl bg-white border"><span className="text-slate-400">Total</span><p className="font-medium mt-1">{formatMoney(detailBooking.totalAmount)}</p></div><div className="p-3 rounded-xl bg-white border"><span className="text-slate-400">Remaining</span><p className="font-medium text-rose-600 mt-1">{formatMoney(detailBooking.remainingAmount)}</p></div></div>
 <div className="p-4 rounded-2xl bg-white border border-slate-200"><h3 className="text-sm font-medium text-slate-900">Assigned Vendors</h3>{detailBooking.assignedVendors?.length?<div className="mt-3 space-y-2">{detailBooking.assignedVendors.map(v=><div key={v.id} className="flex items-center justify-between py-2 border-b last:border-0 text-xs"><span>{v.vendorName}</span><span className="text-slate-400">Vendor assigned</span></div>)}</div>:<p className="text-xs text-slate-400 mt-2">No vendor assigned.</p>}</div>
 <div className="p-4 rounded-2xl bg-white border border-slate-200"><div className="flex items-center justify-between gap-3"><div><h3 className="text-sm font-medium text-slate-900">Add Client Payment</h3><p className="text-[11px] text-slate-500 mt-0.5">Record an advance or remaining payment without leaving this window.</p></div><span className="text-xs text-slate-500">Due {formatMoney(detailBooking.remainingAmount)}</span></div><div className="flex gap-2 mt-3"><input id="booking-payment-input" type="number" min="0.01" max={Number(detailBooking.remainingAmount||0)} value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)} placeholder="Amount paid" className="flex-1 px-3 py-2.5 rounded-xl border border-slate-200 text-sm"/><button type="button" disabled={savingAction||Number(paymentAmount||0)<=0} onClick={handlePayment} className="px-4 py-2.5 rounded-xl bg-slate-900 text-white text-xs font-medium">{savingAction?'Saving...':'Save Payment'}</button></div></div>
 <div className="space-y-3 text-sm"><div className="flex items-start gap-2"><MapPin className="w-4 h-4 text-slate-400 mt-0.5"/><span><strong>Venue:</strong> {detailBooking.venue||'Not specified'}</span></div><div className="flex items-start gap-2"><Users className="w-4 h-4 text-slate-400 mt-0.5"/><span><strong>Guests:</strong> {detailBooking.guestCount||0}</span></div><div className="p-3 rounded-xl bg-slate-50 text-xs"><strong>Package:</strong> {detailBooking.package||'Not specified'}</div>{detailBooking.notes&&<div className="p-3 rounded-xl bg-slate-50 text-xs"><strong>Notes:</strong> {detailBooking.notes}</div>}</div></div></Modal>}
 </div>;
};