import React, { useEffect, useState } from 'react';
import { Plus, UtensilsCrossed, Pencil, Trash2 } from 'lucide-react';
import { MenuItem, BusinessProfile } from '../../types';

const KEY='together-events-menus-v1';
const loadMenus=():MenuItem[]=>{try{const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw):[]}catch{return[]}};

interface MenusViewProps { profile?:BusinessProfile; }
export const MenusView:React.FC<MenusViewProps>=({profile})=>{
 const money=(n:number)=>`${profile?.currencySymbol||'Rs. '}${Number(n||0).toLocaleString()}`;
 const [menus,setMenus]=useState<MenuItem[]>([]); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<MenuItem|null>(null); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [price,setPrice]=useState('');
 useEffect(()=>setMenus(loadMenus()),[]);
 const persist=(next:MenuItem[])=>{setMenus(next);localStorage.setItem(KEY,JSON.stringify(next));};
 const openAdd=()=>{setEditing(null);setName('');setDescription('');setPrice('');setOpen(true)};
 const openEdit=(m:MenuItem)=>{setEditing(m);setName(m.name);setDescription(m.description||'');setPrice(m.price!=null?String(m.price):'');setOpen(true)};
 const save=()=>{if(!name.trim()){alert('Please enter a menu name.');return} const item:MenuItem={id:editing?.id||'menu-'+Date.now(),name:name.trim(),description:description.trim(),price:price?Number(price):undefined,createdAt:editing?.createdAt||new Date().toISOString()};persist(editing?menus.map(m=>m.id===editing.id?item:m):[...menus,item]);setOpen(false)};
 const remove=(id:string)=>{if(window.confirm('Delete this menu?'))persist(menus.filter(m=>m.id!==id))};
 return <div className="space-y-6 animate-in fade-in duration-150"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold tracking-tight text-[#0f172a]">Menus</h1><p className="text-slate-500 text-sm mt-0.5">Create Menu 1, Menu 2, Menu 3 or any custom menu and use it in invoices.</p></div><button type="button" onClick={openAdd} className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-[#0f172a] text-white text-sm font-semibold"><Plus className="w-4 h-4"/>Add Menu</button></div>
 <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{menus.length===0?<div className="glass-card p-8 md:col-span-2 xl:col-span-3 text-center"><UtensilsCrossed className="w-8 h-8 mx-auto text-slate-400 mb-3"/><p className="font-semibold text-slate-700">No menus yet</p><p className="text-sm text-slate-400 mt-1">Add your first menu.</p></div>:menus.map(m=><div key={m.id} className="glass-card p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-lg text-[#0f172a]">{m.name}</h3>{m.description&&<p className="text-sm text-slate-500 mt-1">{m.description}</p>}{m.price!=null&&<p className="text-sm font-semibold text-slate-700 mt-3">{money(m.price)}</p>}</div><div className="flex gap-1"><button type="button" onClick={()=>openEdit(m)} className="p-2 rounded-lg hover:bg-slate-100" aria-label="Edit menu"><Pencil className="w-4 h-4"/></button><button type="button" onClick={()=>remove(m.id)} className="p-2 rounded-lg hover:bg-rose-50 text-rose-500" aria-label="Delete menu"><Trash2 className="w-4 h-4"/></button></div></div></div>)}</div>
 {open&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-900/30 backdrop-blur-sm p-4"><div className="w-full max-w-md rounded-2xl bg-white shadow-2xl p-6"><h2 className="text-lg font-semibold text-slate-900">{editing?'Edit Menu':'Add Menu'}</h2><div className="space-y-4 mt-5"><div><label className="text-xs font-semibold text-slate-600">Menu Name</label><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Menu 1" className="mt-1 w-full px-3 py-2.5 rounded-xl border border-slate-200 outline-none focus:ring-2 focus:ring-slate-900"/></div><div><label className="text-xs font-semibold text-slate-600">Description</label><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Optional description" className="mt-1 w-full px-3 py-2.5 rounded-xl border border-slate-200 outline-none focus:ring-2 focus:ring-slate-900"/></div><div><label className="text-xs font-semibold text-slate-600">Price (optional)</label><input type="number" min="0" value={price} onChange={e=>setPrice(e.target.value)} placeholder="0" className="mt-1 w-full px-3 py-2.5 rounded-xl border border-slate-200 outline-none focus:ring-2 focus:ring-slate-900"/></div></div><div className="flex justify-end gap-2 mt-6"><button type="button" onClick={()=>setOpen(false)} className="px-4 py-2 rounded-xl border border-slate-200 text-sm">Cancel</button><button type="button" onClick={save} className="px-4 py-2 rounded-xl bg-[#0f172a] text-white text-sm font-semibold">Save Menu</button></div></div></div>}</div>;
};
